/**
 * Default configuration and rules shipped with the PM Agent package.
 * These are used as fallback values and reference documentation.
 * Users can generate their own copies via `pm init`.
 */

export const DEFAULT_CONFIG_TOML: string = `# PM Agent Configuration
# Generated by \`pm init\`. Edit to match your project.

[project]
# Your project name — used for database naming and status output
name = ""

# Absolute path to your project root
root = ""

# Optional project description
description = ""

[memory]
# Path to the SQLite database file
path = ""

# Number of days to retain historical data
retention_days = 365

[rules]
# Enable/disable the rules engine globally
enabled = true

# Path to the rules.toml file
config_path = ""

[scan]
# Glob patterns to exclude from scanning
exclude_patterns = ["node_modules", "dist", ".git"]

# Maximum file size (in MB) to index
max_file_size_mb = 1

# Whether to follow symbolic links
follow_symlinks = false

# Enable file watching for incremental re-scanning
watch_enabled = false
`;

export const DEFAULT_RULES_TOML: string = `# ── PM Agent Default Rules ───────────────────────────────────────
# Created by \`pm init\`. Edit at: ~/.config/pm-agent/rules.toml
#
# Rules enforce PM discipline and coding standards.
# Severity: hard (blocks), soft (confirm), info (notify)

# ── PM Discipline ────────────────────────────────────────────────

[[rule]]
scope = "pm"
name = "decision-before-close"
trigger = "ticket.status_change == 'closed'"
condition = "ticket.decisions.count == 0"
action = "block: 'Cannot close {ticket.id}: no decision logged. Run \`pm log\` first.'"
severity = "hard"
description = "Ensures every closed ticket has a corresponding decision record"

[[rule]]
scope = "pm"
name = "scope-check"
trigger = "sprint.proposed_addition"
condition = "sprint.impact_days > sprint.remaining_days * 0.5"
action = "confirm: 'Adding \\\"{sprint.proposed_feature}\\\" adds {sprint.impact_days} days to a sprint with {sprint.remaining_days} days remaining. Proceed?'"
severity = "soft"
description = "Flags scope changes that consume more than 50% of remaining sprint capacity"

[[rule]]
scope = "pm"
name = "daily-blocker-check"
trigger = "time == '09:00'"
condition = "blockers.count > 0"
action = "notify: 'You have {blockers.count} active blockers today: {blockers.list}'"
severity = "info"
description = "Daily reminder to check and resolve blockers"

# ── Code Discipline ──────────────────────────────────────────────

[[rule]]
scope = "code"
name = "no-console-log"
trigger = "file.saved"
condition = "file.path == 'src/**/*.ts' && file.contains('console.log')"
action = "suggest: 'Remove console.log before committing. Use a logger instead.'"
severity = "soft"
description = "Reminds developers to remove debugging console.log statements"

[[rule]]
scope = "code"
name = "no-direct-api-calls"
trigger = "file.path == 'src/**/*.ts'"
condition = "file.contains('api.')"
action = "block: 'Direct API calls not allowed in {file.path}'"
severity = "hard"
description = "Blocks direct API calls in source files"
`;
