/**
 * Default configuration and rules shipped with the PM Agent package.
 * These are used as fallback values and reference documentation.
 * Users can generate their own copies via `pm init`.
 */

export const DEFAULT_CONFIG_TOML: string = `# PM Agent Configuration
# Generated by \`pm init\` in .pm-agent/ (project-local).
# Edit to match your project.

[project]
# Your project name — used for database naming and status output
name = ""

# Absolute path to your project root
root = ""

# Optional project description
description = ""

[memory]
# Path to the SQLite database file (inside .pm-agent/)
path = ""

# Number of days to retain historical data
retention_days = 365

[rules]
# Enable/disable the rules engine globally
enabled = true

# Path to the rules.toml file (inside .pm-agent/)
config_path = ""

[scan]
# Glob patterns to exclude from scanning
exclude_patterns = ["node_modules", "dist", ".git"]

# Maximum file size (in MB) to index
max_file_size_mb = 1

# Whether to follow symbolic links
follow_symlinks = false

# Enable file watching for incremental re-scanning
watch_enabled = false
`;

export const DEFAULT_RULES_TOML: string = `# ── PM Agent Default Rules ───────────────────────────────────────
# Created by \`pm init\` in .pm-agent/ (project-local).
#
# Rules enforce PM discipline and coding standards.
# Severity: hard (blocks), soft (confirm), info (notify)
#
# Auto-enforcement is active on every tool call.
# Available context variables:
#   tool_name   — the MCP tool being called (e.g. "pm_log_decision")
#   operation   — inferred operation: read / log / add / scan / enforce / ...
#   entity      — inferred target: context / decision / note / rule / ...
#   tool_args   — the full arguments object passed to the tool
#   <arg-name>  — each tool argument is available directly (e.g. title, body)
# Triggers are boolean expressions. Use ==, !=, contains(), &&, ||.

# ── PM Discipline ────────────────────────────────────────────────

[[rule]]
scope = "pm"
name = "decision-before-close"
trigger = "ticket.status_change == 'closed'"
condition = "ticket.decisions.count == 0"
action = "block: 'Cannot close {ticket.id}: no decision logged. Run \`pm log\` first.'"
severity = "hard"
description = "Ensures every closed ticket has a corresponding decision record"

[[rule]]
scope = "pm"
name = "scope-check"
trigger = "sprint.proposed_addition"
condition = "sprint.impact_days > sprint.remaining_days * 0.5"
action = "confirm: 'Adding \\\"{sprint.proposed_feature}\\\" adds {sprint.impact_days} days to a sprint with {sprint.remaining_days} days remaining. Proceed?'"
severity = "soft"
description = "Flags scope changes that consume more than 50% of remaining sprint capacity"

[[rule]]
scope = "pm"
name = "daily-blocker-check"
trigger = "time == '09:00'"
condition = "blockers.count > 0"
action = "notify: 'You have {blockers.count} active blockers today: {blockers.list}'"
severity = "info"
description = "Daily reminder to check and resolve blockers"

# ── Code Discipline ──────────────────────────────────────────────

[[rule]]
scope = "code"
name = "no-console-log"
trigger = "file.saved"
condition = "file.path == 'src/**/*.ts' && file.contains('console.log')"
action = "suggest: 'Remove console.log before committing. Use a logger instead.'"
severity = "soft"
description = "Reminds developers to remove debugging console.log statements"

[[rule]]
scope = "code"
name = "no-direct-api-calls"
trigger = "file.path == 'src/**/*.ts'"
condition = "file.contains('api.')"
action = "block: 'Direct API calls not allowed in {file.path}'"
severity = "hard"
description = "Blocks direct API calls in source files"

# ── Auto-Enforcement Rules ───────────────────────────────────────
# These rules are evaluated automatically on every tool call.
# The context includes tool_name, operation, entity, and all tool arguments.
# Write triggers as boolean expressions referencing these variables.
#
# Guide for writing auto-enforceable rules:
# - tool_name == 'pm_log_decision'  — fires when logging a decision
# - tool_name == 'pm_log_note'      — fires when logging a note
# - tool_name == 'pm_add_rule'      — fires when adding a rule
# - body.contains('architecture')   — checks if arg "body" contains text
# - title && title.contains('X')    — safe check (guards against null)
# - Use && for AND, || for OR

[[rule]]
scope = "all"
name = "ask-permission-major-decisions"
trigger = "tool_name == 'pm_log_decision'"
condition = "body && (body.contains('architecture') || body.contains('scope') || body.contains('significant'))"
action = "block: 'Decision may affect project direction ({title}). Ask the user for explicit permission before logging significant decisions.'"
severity = "hard"
description = "Blocks logging decisions that touch architecture, scope, or significant changes without permission."

[[rule]]
scope = "all"
name = "confirm-scope-changes"
trigger = "tool_name == 'pm_log_decision'"
condition = "title && (title.contains('scope') || title.contains('sprint'))"
action = "confirm: 'Are you sure this scope-affecting decision is approved? Title: {title}'"
severity = "soft"
description = "Confirms scope-related decisions before logging them."

[[rule]]
scope = "all"
name = "alert-on-git-refs-in-notes"
trigger = "tool_name == 'pm_log_note'"
condition = "content && (content.contains('git push') || content.contains('git commit'))"
action = "notify: 'Note references a git write operation ({content}). Ensure the user has approved this action.'"
severity = "info"
description = "Raises awareness when notes reference git push or commit operations."
`;
